name = "EasyFit"
uuid = "fde71243-0cda-4261-b7c7-4845bd106b21"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br>"]
version = "0.5.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Interpolations = "0.12.10, 0.13"
LsqFit = "0.11.0"
Parameters = "0.12.1"
julia = "1"
